import os

p = 'C:/Users/mbkhn/Downloads/Inspired/claude-bull/.superpowers/brainstorm/4977-1773332353/readability-approaches.html'

lines = [
'<!DOCTYPE html>',
'<html lang="en">',
'<head>',
'<meta charset="UTF-8">',
'<meta name="viewport" content="width=device-width, initial-scale=1.0">',
'<title>Research Step Layout Options</title>',
'<style>',
'*{box-sizing:border-box;margin:0;padding:0}',
'body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;background:#0f0f12;color:#e0e0e0;padding:28px 24px}',
'h1{font-size:18px;font-weight:600;margin-bottom:6px}',
'.sub{font-size:13px;color:#666;margin-bottom:28px;line-height:1.5}',
'.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:24px}',
'@media(max-width:900px){.cards{grid-template-columns:1fr}}',
'article.card{background:#141416;border:2px solid #242428;border-radius:10px;overflow:hidden;transition:border-color .15s,transform .1s}',
'article.card:hover{border-color:#3a3a3e;transform:translateY(-2px)}',
'article.card.selected{border-color:#4a8c5c;background:#121a14}',
'button.card-btn{display:block;width:100%;background:none;border:none;padding:0;cursor:pointer;text-align:left;font-family:inherit}',
'.card-image{background:#0c0c0e;padding:14px;min-height:265px}',
'.card-body{padding:12px 14px;border-top:1px solid #1e1e22}',
'.card-body h3{font-size:13px;font-weight:600;margin-bottom:5px;color:#ebebeb}',
'.card-body p{font-size:12px;color:#666;line-height:1.5}',
'.note{background:#141416;border:1px solid #242428;border-radius:6px;padding:16px;font-size:13px;color:#666;line-height:1.7}',
'.chip{background:#1c1c1f;border:1px solid #242428;border-radius:4px;padding:6px 10px;display:inline-block}',
'.chips-row{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:10px}',
'.kf{background:#111;border:1px solid #2a2a2e;border-left:3px solid #4a8c5c;border-radius:5px;padding:10px 12px;margin-bottom:10px}',
'.prose{font-size:11px;color:#777;line-height:1.7;background:#111;border:1px solid #1e1e22;border-radius:4px;padding:9px;margin-top:4px}',
'.split{display:flex;gap:10px}',
'.sidebar-p{width:100px;flex-shrink:0;display:flex;flex-direction:column;gap:7px}',
'.scard{background:#111;border:1px solid #242428;border-radius:5px;padding:8px}',
'.slabel{font-size:9px;color:#4c4c52;text-transform:uppercase;letter-spacing:.06em;margin-bottom:3px}',
'.dp-list{margin-bottom:10px}',
'.dp-row{display:flex;gap:8px;align-items:flex-start;margin-bottom:8px}',
'.dp-n{width:16px;height:16px;border-radius:50%;border:1px solid #4a8c5c;display:flex;align-items:center;justify-content:center;font-size:8px;color:#4a8c5c;flex-shrink:0;margin-top:1px}',
'.dp-n.bear{border-color:#c0392b;color:#c0392b}',
'.dp-t{font-size:11px;color:#ebebeb;line-height:1.45}',
'.cit{font-size:10px;color:#4c4c52}',
'</style>',
'</head>',
'<body>',
'<main>',
'<h1>How should each research step show information?</h1>',
'<p class="sub">Right now everything is a wall of text. These 3 approaches make it scannable &mdash; pick your favorite.</p>',
'',
'<section class="cards" aria-label="Layout option choices">',
'',
'<article class="card" id="card-a">',
'<button class="card-btn" onclick="pick(\'a\')" aria-pressed="false" id="btn-a">',
'<div class="card-image">',
'<div class="kf">',
'<div style="font-size:9px;color:#4c4c52;text-transform:uppercase;margin-bottom:3px">Key Finding &middot; Step 3 &middot; <span style="color:#4a8c5c">BULLISH</span></div>',
'<div style="font-size:12px;font-weight:500;color:#ebebeb;line-height:1.5">Revenue grew 9% YoY to $391B with 29% operating margins &mdash; structurally sound.</div>',
'</div>',
'<div class="chips-row">',
'<div class="chip"><div style="font-size:9px;color:#4c4c52">Revenue</div><div style="font-size:13px;font-weight:600;color:#ebebeb">$391B</div><div style="font-size:10px;color:#4a8c5c">+9% YoY</div></div>',
'<div class="chip"><div style="font-size:9px;color:#4c4c52">Op Margin</div><div style="font-size:13px;font-weight:600;color:#ebebeb">29.6%</div><div style="font-size:10px;color:#4a8c5c">+2.1pp</div></div>',
'<div class="chip"><div style="font-size:9px;color:#4c4c52">Free CF</div><div style="font-size:13px;font-weight:600;color:#ebebeb">$112B</div><div style="font-size:10px;color:#888">LTM</div></div>',
'<div class="chip"><div style="font-size:9px;color:#4c4c52">Net Debt</div><div style="font-size:13px;font-weight:600;color:#ebebeb">-$67B</div><div style="font-size:10px;color:#888">Net Cash</div></div>',
'</div>',
'<div class="prose">Apple FY2024 performance demonstrated resilience with Services revenue growing 13% to record levels...',
'<div style="margin-top:6px"><a href="#" style="color:#4a8c5c;font-size:10px;text-decoration:none">&#8599; View 10-K on SEC.gov</a></div>',
'</div>',
'</div>',
'<div class="card-body"><h3>A &middot; Metric Chips</h3><p>Key numbers in quick-scan cards above AI prose. Numbers pop first, analysis explains why.</p></div>',
'</button>',
'</article>',
'',
'<article class="card" id="card-b">',
'<button class="card-btn" onclick="pick(\'b\')" aria-pressed="false" id="btn-b">',
'<div class="card-image">',
'<div class="split">',
'<aside class="sidebar-p">',
'<div class="scard"><div class="slabel">Verdict</div><div style="font-size:12px;font-weight:600;color:#4a8c5c">BULLISH</div></div>',
'<div class="scard"><div class="slabel">Numbers</div>',
'<div style="font-size:10px;color:#888;line-height:1.9"><strong style="font-size:12px;color:#ebebeb">$391B</strong><br>Revenue<br><strong style="font-size:12px;color:#ebebeb">29.6%</strong><br>Margin<br><strong style="font-size:12px;color:#ebebeb">$112B</strong><br>FCF</div>',
'</div>',
'<div class="scard"><div class="slabel">Source</div>',
'<div style="font-size:10px;color:#4a8c5c;line-height:2.0">10-K &sect;7 &#8599;<br>10-K &sect;8 &#8599;</div>',
'</div>',
'</aside>',
'<div style="flex:1;display:flex;flex-direction:column;gap:8px">',
'<div class="kf"><div style="font-size:12px;font-weight:500;color:#ebebeb;line-height:1.5">Revenue grew 9% to $391B with 29% margins.</div></div>',
'<div class="prose">Apple FY2024 demonstrated resilience despite macro headwinds. Services grew 13% to record levels, offsetting iPhone softness in China...</div>',
'</div>',
'</div>',
'</div>',
'<div class="card-body"><h3>B &middot; Side Panel</h3><p>Numbers and sources pinned in a left sidebar. Scan numbers while reading analysis side-by-side.</p></div>',
'</button>',
'</article>',
'',
'<article class="card" id="card-c">',
'<button class="card-btn" onclick="pick(\'c\')" aria-pressed="false" id="btn-c">',
'<div class="card-image">',
'<div style="font-size:9px;color:#4c4c52;text-transform:uppercase;letter-spacing:.06em;margin-bottom:8px">Data Points &middot; <span style="color:#4a8c5c">BULLISH</span></div>',
'<div class="dp-list">',
'<div class="dp-row"><div class="dp-n">1</div><div class="dp-t">Revenue: <strong style="color:#4a8c5c">$391B</strong> (+9% YoY) <span class="cit">[10-K &sect;7]</span></div></div>',
'<div class="dp-row"><div class="dp-n">2</div><div class="dp-t">Op margin expanded <strong style="color:#4a8c5c">+2.1pp</strong> to 29.6% <span class="cit">[10-K &sect;8]</span></div></div>',
'<div class="dp-row"><div class="dp-n bear">3</div><div class="dp-t">iPhone revenue <strong style="color:#c0392b">-1%</strong> YoY; China declining <span class="cit">[10-K &sect;1A]</span></div></div>',
'<div class="dp-row"><div class="dp-n">4</div><div class="dp-t">Services gross margin <strong style="color:#4a8c5c">74.6%</strong> &mdash; record high <span class="cit">[10-K &sect;8]</span></div></div>',
'</div>',
'<div style="background:#111;border:1px solid #1e1e22;border-radius:4px;padding:8px">',
'<div style="font-size:10px;color:#4c4c52;display:flex;justify-content:space-between;margin-bottom:5px"><span>Full analysis</span><span>&#9660;</span></div>',
'<div class="prose" style="background:transparent;border:none;padding:0">Apple FY2024 demonstrated resilience despite macro headwinds...</div>',
'</div>',
'</div>',
'<div class="card-body"><h3>C &middot; Numbered Facts</h3><p>Each finding as its own row &mdash; green=bullish, red=bearish. Full prose collapses below.</p></div>',
'</button>',
'</article>',
'',
'</section>',
'',
'<p class="note">',
'<strong style="color:#ebebeb">All 3 include:</strong> real SEC.gov links, bar chart for Step 3 (revenue trend), valuation gauge for Step 6, and a "View Memo &rarr;" button in the footer once all steps are done.',
'<br><br>',
'<strong style="color:#ebebeb">Click an option above</strong> or just tell me A, B, or C in the terminal!',
'</p>',
'</main>',
'',
'<script>',
'function pick(id) {',
'  ["a","b","c"].forEach(function(x) {',
'    document.getElementById("card-"+x).classList.remove("selected");',
'    document.getElementById("btn-"+x).setAttribute("aria-pressed","false");',
'  });',
'  document.getElementById("card-"+id).classList.add("selected");',
'  document.getElementById("btn-"+id).setAttribute("aria-pressed","true");',
'  try {',
'    fetch("/__select", {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({choice:id,text:"Option "+id.toUpperCase()})}).catch(function(){});',
'  } catch(e) {}',
'}',
'</script>',
'</body>',
'</html>',
]

with open(p, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print('written', os.path.getsize(p), 'bytes')
